// ⚠️ THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-point-path.ts
// Source: src/types/path/fieldDefinitions.ts
// To modify: Update fieldDefinitions.ts and run: npm run generate:point

import { toDegrees } from '@/utils/';
import { AbstractPath } from './AbstractPath';
import { Point, PointField } from './Point';
export abstract class GeneratedPath extends AbstractPath {
    // === Coordinates Accessors ===

    getLatitude(pointIndex: number): number {
        return super.getField(pointIndex, PointField.LATITUDE);
    }

    getLatitudeDeg(pointIndex: number): number {
        return toDegrees(super.getField(pointIndex, PointField.LATITUDE));
    }

    setLatitude(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.LATITUDE, value);
    }

    getLongitude(pointIndex: number): number {
        return super.getField(pointIndex, PointField.LONGITUDE);
    }

    getLongitudeDeg(pointIndex: number): number {
        return toDegrees(super.getField(pointIndex, PointField.LONGITUDE));
    }

    setLongitude(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.LONGITUDE, value);
    }

    getDistance(pointIndex: number): number {
        return super.getField(pointIndex, PointField.DISTANCE);
    }

    setDistance(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.DISTANCE, value);
    }

    // === Temporal Accessors ===

    getTime(pointIndex: number): number {
        return super.getField(pointIndex, PointField.TIME);
    }

    setTime(pointIndex: number, value: number | Date): void {
        const timestamp = value instanceof Date ? value.getTime() : value;
        super.setField(pointIndex, PointField.TIME, timestamp);
    }

    getTimeAsDate(pointIndex: number): Date {
        return new Date(this.getTime(pointIndex));
    }

    getElapsed(pointIndex: number): number {
        return super.getField(pointIndex, PointField.ELAPSED);
    }

    setElapsed(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.ELAPSED, value);
    }

    // === Angles Accessors ===

    getBearing(pointIndex: number): number {
        return super.getField(pointIndex, PointField.BEARING);
    }

    setBearing(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.BEARING, value);
    }

    // === 🏔️ Elevation Accessors ===

    getElevation(pointIndex: number): number {
        return super.getField(pointIndex, PointField.ELEVATION);
    }

    setElevation(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.ELEVATION, value);
    }

    // === 📐 Grade Accessors ===

    getGrade(pointIndex: number): number {
        return super.getField(pointIndex, PointField.GRADE);
    }

    setGrade(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.GRADE, value);
    }

    // === Radius Accessors ===

    getRadius(pointIndex: number): number {
        return super.getField(pointIndex, PointField.RADIUS);
    }

    setRadius(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.RADIUS, value);
    }

    // === Aero coef Accessors ===

    getAeroCoef(pointIndex: number): number {
        return super.getField(pointIndex, PointField.AERO_COEF);
    }

    setAeroCoef(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.AERO_COEF, value);
    }

    // === Cyclist wind Accessors ===

    getWindBearing(pointIndex: number): number {
        return super.getField(pointIndex, PointField.WIND_BEARING);
    }

    setWindBearing(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.WIND_BEARING, value);
    }

    getWindAlpha(pointIndex: number): number {
        return super.getField(pointIndex, PointField.WIND_ALPHA);
    }

    setWindAlpha(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.WIND_ALPHA, value);
    }

    // === ⚡ Power Physics Accessors ===

    getPAero(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_AERO);
    }

    setPAero(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_AERO, value);
    }

    getPGravity(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_GRAVITY);
    }

    setPGravity(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_GRAVITY, value);
    }

    getPRollingResistance(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_ROLLING_RESISTANCE);
    }

    setPRollingResistance(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_ROLLING_RESISTANCE, value);
    }

    getPWheelBearings(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_WHEEL_BEARINGS);
    }

    setPWheelBearings(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_WHEEL_BEARINGS, value);
    }

    // === ⚡ Power Cyclist Accessors ===

    getPInputPower(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_INPUT_POWER);
    }

    setPInputPower(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_INPUT_POWER, value);
    }

    getPCyclistProvidedOptimalPower(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_CYCLIST_PROVIDED_OPTIMAL_POWER);
    }

    setPCyclistProvidedOptimalPower(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_CYCLIST_PROVIDED_OPTIMAL_POWER, value);
    }

    getPCyclistProvidedOptimalPowerWithHarmonics(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_CYCLIST_PROVIDED_OPTIMAL_POWER_HARMONICS);
    }

    setPCyclistProvidedOptimalPowerWithHarmonics(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_CYCLIST_PROVIDED_OPTIMAL_POWER_HARMONICS, value);
    }

    getPCyclistPowerNeeded(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_CYCLIST_PROVIDED_POWER_NEEDED);
    }

    setPCyclistPowerNeeded(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_CYCLIST_PROVIDED_POWER_NEEDED, value);
    }

    getPCyclistProvidedMuscular(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_CYCLIST_PROVIDED_MUSCULAR);
    }

    setPCyclistProvidedMuscular(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_CYCLIST_PROVIDED_MUSCULAR, value);
    }

    getPCyclistProvidedWheel(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_CYCLIST_PROVIDED_WHEEL);
    }

    setPCyclistProvidedWheel(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_CYCLIST_PROVIDED_WHEEL, value);
    }

    // === ⚡ Power Post processed Accessors ===

    getPComputedTotalPower(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_COMPUTED_TOTAL_POWER);
    }

    setPComputedTotalPower(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_COMPUTED_TOTAL_POWER, value);
    }

    getPComputedWheelPower(pointIndex: number): number {
        return super.getField(pointIndex, PointField.P_COMPUTED_WHEEL_POWER);
    }

    setPComputedWheelPower(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.P_COMPUTED_WHEEL_POWER, value);
    }

    getPComputedPower(pointIndex: number): number {
        return super.getField(pointIndex, PointField.POWER);
    }

    setPComputedPower(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.POWER, value);
    }

    // === Speed & Motion Accessors ===

    getSpeed(pointIndex: number): number {
        return super.getField(pointIndex, PointField.SPEED);
    }

    setSpeed(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.SPEED, value);
    }

    getSpeedMax(pointIndex: number): number {
        return super.getField(pointIndex, PointField.SPEED_MAX);
    }

    setSpeedMax(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.SPEED_MAX, value);
    }

    getSpeedMaxIncline(pointIndex: number): number {
        return super.getField(pointIndex, PointField.SPEED_MAX_INCLINE);
    }

    setSpeedMaxIncline(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.SPEED_MAX_INCLINE, value);
    }

    getVirtSpeedCurrent(pointIndex: number): number {
        return super.getField(pointIndex, PointField.VIRT_SPEED_CURRENT);
    }

    setVirtSpeedCurrent(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.VIRT_SPEED_CURRENT, value);
    }

    // === Environmental Accessors ===

    getTemperature(pointIndex: number): number {
        return super.getField(pointIndex, PointField.TEMPERATURE);
    }

    setTemperature(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.TEMPERATURE, value);
    }

    getWindSpeed(pointIndex: number): number {
        return super.getField(pointIndex, PointField.WIND_SPEED);
    }

    setWindSpeed(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.WIND_SPEED, value);
    }

    getWindDirection(pointIndex: number): number {
        return super.getField(pointIndex, PointField.WIND_DIRECTION);
    }

    setWindDirection(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.WIND_DIRECTION, value);
    }

    // === Physiological Accessors ===

    getHeartRate(pointIndex: number): number {
        return super.getField(pointIndex, PointField.HEART_RATE);
    }

    setHeartRate(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.HEART_RATE, value);
    }

    getCadence(pointIndex: number): number {
        return super.getField(pointIndex, PointField.CADENCE);
    }

    setCadence(pointIndex: number, value: number): void {
        super.setField(pointIndex, PointField.CADENCE, value);
    }

    /**
     * Adds a new point with the provided data.
     * @param data Complete point data with all 34 properties
     * @returns The index of the newly added point
     */
    addPoint(data: Point): number {
        const pointIndex = this.pointCount;
        this.ensureCapacity(pointIndex + 1);

        // Increment point count first so bounds checking works
        this.pointCount++;

        // Set all fields from the provided data
        // Coordinates
        this.setLatitude(pointIndex, data.latitude);
        this.setLongitude(pointIndex, data.longitude);
        this.setDistance(pointIndex, data.distance);

        // Temporal
        this.setTime(pointIndex, data.time);
        this.setElapsed(pointIndex, data.elapsed);

        // Angles
        this.setBearing(pointIndex, data.bearing);

        // 🏔️ Elevation
        this.setElevation(pointIndex, data.elevation);

        // 📐 Grade
        this.setGrade(pointIndex, data.grade);

        // Radius
        this.setRadius(pointIndex, data.radius);

        // Aero coef
        this.setAeroCoef(pointIndex, data.aeroCoef);

        // Cyclist wind
        this.setWindBearing(pointIndex, data.windBearing);
        this.setWindAlpha(pointIndex, data.windAlpha);

        // ⚡ Power Physics
        this.setPAero(pointIndex, data.pAero);
        this.setPGravity(pointIndex, data.pGravity);
        this.setPRollingResistance(pointIndex, data.pRollingResistance);
        this.setPWheelBearings(pointIndex, data.pWheelBearings);

        // ⚡ Power Cyclist
        this.setPInputPower(pointIndex, data.pInputPower);
        this.setPCyclistProvidedOptimalPower(pointIndex, data.pCyclistProvidedOptimalPower);
        this.setPCyclistProvidedOptimalPowerWithHarmonics(
            pointIndex,
            data.pCyclistProvidedOptimalPowerWithHarmonics
        );
        this.setPCyclistPowerNeeded(pointIndex, data.pCyclistPowerNeeded);
        this.setPCyclistProvidedMuscular(pointIndex, data.pCyclistProvidedMuscular);
        this.setPCyclistProvidedWheel(pointIndex, data.PCyclistProvidedWheel);

        // ⚡ Power Post processed
        this.setPComputedTotalPower(pointIndex, data.pComputedTotalPower);
        this.setPComputedWheelPower(pointIndex, data.pComputedWheelPower);
        this.setPComputedPower(pointIndex, data.pComputedPower);

        // Speed & Motion
        this.setSpeed(pointIndex, data.speed);
        this.setSpeedMax(pointIndex, data.speedMax);
        this.setSpeedMaxIncline(pointIndex, data.speedMaxIncline);
        this.setVirtSpeedCurrent(pointIndex, data.virtSpeedCurrent);

        // Environmental
        this.setTemperature(pointIndex, data.temperature);
        this.setWindSpeed(pointIndex, data.windSpeed);
        this.setWindDirection(pointIndex, data.windDirection);

        // Physiological
        this.setHeartRate(pointIndex, data.heartRate);
        this.setCadence(pointIndex, data.cadence);

        return pointIndex;
    }

    /**
     * Gets all data for a specific point.
     */
    getPointData(pointIndex: number): Point {
        return {
            // Coordinates
            latitude: this.getLatitude(pointIndex),
            longitude: this.getLongitude(pointIndex),
            distance: this.getDistance(pointIndex),
            // Temporal
            time: this.getTime(pointIndex),
            elapsed: this.getElapsed(pointIndex),
            // Angles
            bearing: this.getBearing(pointIndex),
            // 🏔️ Elevation
            elevation: this.getElevation(pointIndex),
            // 📐 Grade
            grade: this.getGrade(pointIndex),
            // Radius
            radius: this.getRadius(pointIndex),
            // Aero coef
            aeroCoef: this.getAeroCoef(pointIndex),
            // Cyclist wind
            windBearing: this.getWindBearing(pointIndex),
            windAlpha: this.getWindAlpha(pointIndex),
            // ⚡ Power Physics
            pAero: this.getPAero(pointIndex),
            pGravity: this.getPGravity(pointIndex),
            pRollingResistance: this.getPRollingResistance(pointIndex),
            pWheelBearings: this.getPWheelBearings(pointIndex),
            // ⚡ Power Cyclist
            pInputPower: this.getPInputPower(pointIndex),
            pCyclistProvidedOptimalPower: this.getPCyclistProvidedOptimalPower(pointIndex),
            pCyclistProvidedOptimalPowerWithHarmonics:
                this.getPCyclistProvidedOptimalPowerWithHarmonics(pointIndex),
            pCyclistPowerNeeded: this.getPCyclistPowerNeeded(pointIndex),
            pCyclistProvidedMuscular: this.getPCyclistProvidedMuscular(pointIndex),
            PCyclistProvidedWheel: this.getPCyclistProvidedWheel(pointIndex),
            // ⚡ Power Post processed
            pComputedTotalPower: this.getPComputedTotalPower(pointIndex),
            pComputedWheelPower: this.getPComputedWheelPower(pointIndex),
            pComputedPower: this.getPComputedPower(pointIndex),
            // Speed & Motion
            speed: this.getSpeed(pointIndex),
            speedMax: this.getSpeedMax(pointIndex),
            speedMaxIncline: this.getSpeedMaxIncline(pointIndex),
            virtSpeedCurrent: this.getVirtSpeedCurrent(pointIndex),
            // Environmental
            temperature: this.getTemperature(pointIndex),
            windSpeed: this.getWindSpeed(pointIndex),
            windDirection: this.getWindDirection(pointIndex),
            // Physiological
            heartRate: this.getHeartRate(pointIndex),
            cadence: this.getCadence(pointIndex),
        };
    }

    // Helper function for strict NaN handling
    protected interpolateValue(v1: number, v2: number, coef: number): number {
        if (isNaN(v1) || isNaN(v2)) {
            return NaN;
        }
        return v1 + (v2 - v1) * coef;
    }

    /**
     * Interpolates a new point between two existing points.
     *
     * Uses linear interpolation for all numeric fields:
     * - result = p1 + (p2 - p1) × coef
     *
     * **NaN Handling (STRICT):**
     * - If either p1 or p2 value is NaN, result is NaN
     * - This ensures data integrity for incomplete GPS data
     *
     * @param index1 Index of first point
     * @param index2 Index of second point
     * @param coef Interpolation coefficient (0 = p1, 1 = p2, 0.5 = midpoint)
     * @returns Interpolated point
     */
    public interpolatePoint(index1: number, index2: number, coef: number): Point {
        const p1 = this.getPointData(index1);
        const p2 = this.getPointData(index2);

        return {
            // Coordinates
            latitude: this.interpolateValue(p1.latitude, p2.latitude, coef),
            longitude: this.interpolateValue(p1.longitude, p2.longitude, coef),
            distance: this.interpolateValue(p1.distance, p2.distance, coef),
            // Temporal
            time: this.interpolateValue(p1.time, p2.time, coef),
            elapsed: this.interpolateValue(p1.elapsed, p2.elapsed, coef),
            // Angles
            bearing: this.interpolateValue(p1.bearing, p2.bearing, coef),
            // 🏔️ Elevation
            elevation: this.interpolateValue(p1.elevation, p2.elevation, coef),
            // 📐 Grade
            grade: this.interpolateValue(p1.grade, p2.grade, coef),
            // Radius
            radius: this.interpolateValue(p1.radius, p2.radius, coef),
            // Aero coef
            aeroCoef: this.interpolateValue(p1.aeroCoef, p2.aeroCoef, coef),
            // Cyclist wind
            windBearing: this.interpolateValue(p1.windBearing, p2.windBearing, coef),
            windAlpha: this.interpolateValue(p1.windAlpha, p2.windAlpha, coef),
            // ⚡ Power Physics
            pAero: this.interpolateValue(p1.pAero, p2.pAero, coef),
            pGravity: this.interpolateValue(p1.pGravity, p2.pGravity, coef),
            pRollingResistance: this.interpolateValue(
                p1.pRollingResistance,
                p2.pRollingResistance,
                coef
            ),
            pWheelBearings: this.interpolateValue(p1.pWheelBearings, p2.pWheelBearings, coef),
            // ⚡ Power Cyclist
            pInputPower: this.interpolateValue(p1.pInputPower, p2.pInputPower, coef),
            pCyclistProvidedOptimalPower: this.interpolateValue(
                p1.pCyclistProvidedOptimalPower,
                p2.pCyclistProvidedOptimalPower,
                coef
            ),
            pCyclistProvidedOptimalPowerWithHarmonics: this.interpolateValue(
                p1.pCyclistProvidedOptimalPowerWithHarmonics,
                p2.pCyclistProvidedOptimalPowerWithHarmonics,
                coef
            ),
            pCyclistPowerNeeded: this.interpolateValue(
                p1.pCyclistPowerNeeded,
                p2.pCyclistPowerNeeded,
                coef
            ),
            pCyclistProvidedMuscular: this.interpolateValue(
                p1.pCyclistProvidedMuscular,
                p2.pCyclistProvidedMuscular,
                coef
            ),
            PCyclistProvidedWheel: this.interpolateValue(
                p1.PCyclistProvidedWheel,
                p2.PCyclistProvidedWheel,
                coef
            ),
            // ⚡ Power Post processed
            pComputedTotalPower: this.interpolateValue(
                p1.pComputedTotalPower,
                p2.pComputedTotalPower,
                coef
            ),
            pComputedWheelPower: this.interpolateValue(
                p1.pComputedWheelPower,
                p2.pComputedWheelPower,
                coef
            ),
            pComputedPower: this.interpolateValue(p1.pComputedPower, p2.pComputedPower, coef),
            // Speed & Motion
            speed: this.interpolateValue(p1.speed, p2.speed, coef),
            speedMax: this.interpolateValue(p1.speedMax, p2.speedMax, coef),
            speedMaxIncline: this.interpolateValue(p1.speedMaxIncline, p2.speedMaxIncline, coef),
            virtSpeedCurrent: this.interpolateValue(p1.virtSpeedCurrent, p2.virtSpeedCurrent, coef),
            // Environmental
            temperature: this.interpolateValue(p1.temperature, p2.temperature, coef),
            windSpeed: this.interpolateValue(p1.windSpeed, p2.windSpeed, coef),
            windDirection: this.interpolateValue(p1.windDirection, p2.windDirection, coef),
            // Physiological
            heartRate: this.interpolateValue(p1.heartRate, p2.heartRate, coef),
            cadence: this.interpolateValue(p1.cadence, p2.cadence, coef),
        };
    }
}
