// ⚠️ THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-point-path.ts
// Source: src/codegen/field-definitions.ts
// To modify: Update field-definitions.ts and run: npm run generate:point

/**
 * Enum defining the index of each field in the chunked array storage.
 * Based on PropertyKeys.java from gpx2web project.
 * Each point has exactly 33 numeric values stored contiguously.
 */
export enum PointField {
    // Spatial & Navigation (7 properties)
    LATITUDE = 0, // Latitude (radians)
    LONGITUDE = 1, // Longitude (radians)
    ELEVATION = 2, // Elevation (meters)
    BEARING = 3, // Direction bearing (radians)
    DISTANCE = 4, // Distance (meters)
    RADIUS = 5, // Turn radius (meters)
    GRADE = 6, // Road grade/slope (%)

    // Temporal (2 properties)
    TIME = 7, // Timestamp (ms since epoch)
    ELAPSED = 8, // Elapsed duration (ms)

    // Physics & Power (13 properties)
    P_INPUT_POWER = 9, // GPX input power
    P_CYCLIST_PROVIDED_OPTIMAL_POWER = 10, // Optimal power
    P_CYCLIST_PROVIDED_POWER_NEEDED = 11, // Power needed
    P_CYCLIST_PROVIDED_MUSCULAR = 12, // Raw cyclist power
    P_CYCLIST_PROVIDED_WHEEL = 13, // Cyclist power transmitted to ground
    AERO_COEF = 14, // Aerodynamic coefficient
    P_AERO = 15, // Aerodynamic power
    P_GRAVITY = 16, // Gravitational power
    P_ROLLING_RESISTANCE = 17, // Rolling resistance power
    P_WHEEL_BEARINGS = 18, // Wheel bearings power
    P_COMPUTED_TOTAL_POWER = 19, // Power from acceleration
    P_COMPUTED_WHEEL_POWER = 20, // Wheel power from acceleration
    POWER = 21, // Total power (watts)

    // Speed & Motion (4 properties)
    SPEED = 22, // Current speed (m/s)
    SPEED_MAX = 23, // Maximum speed (m/s)
    SPEED_MAX_INCLINE = 24, // Max speed on incline (m/s)
    VIRT_SPEED_CURRENT = 25, // Virtual current speed (m/s)

    // Environmental (5 properties)
    TEMPERATURE = 26, // Temperature (celsius)
    WIND_SPEED = 27, // Wind speed (m/s)
    WIND_DIRECTION = 28, // Wind direction (radians)
    WIND_BEARING = 29, // Wind bearing (radians)
    WIND_ALPHA = 30, // Wind angle (radians)

    // Physiological (2 properties)
    HEART_RATE = 31, // Heart rate (bpm)
    CADENCE = 32, // Pedaling cadence (rpm)
}

export enum PointFieldName {
    // Spatial & Navigation (7 properties)
    latitude = 'latitude', // Latitude (radians)
    longitude = 'longitude', // Longitude (radians)
    elevation = 'elevation', // Elevation (meters)
    bearing = 'bearing', // Direction bearing (radians)
    distance = 'distance', // Distance (meters)
    radius = 'radius', // Turn radius (meters)
    grade = 'grade', // Road grade/slope (%)

    // Temporal (2 properties)
    time = 'time', // Timestamp (ms since epoch)
    elapsed = 'elapsed', // Elapsed duration (ms)

    // Physics & Power (13 properties)
    pInputPower = 'pInputPower', // GPX input power
    pCyclistProvidedOptimalPower = 'pCyclistProvidedOptimalPower', // Optimal power
    pCyclistPowerNeeded = 'pCyclistPowerNeeded', // Power needed
    pCyclistProvidedMuscular = 'pCyclistProvidedMuscular', // Raw cyclist power
    PCyclistProvidedWheel = 'PCyclistProvidedWheel', // Cyclist power transmitted to ground
    aeroCoef = 'aeroCoef', // Aerodynamic coefficient
    pAero = 'pAero', // Aerodynamic power
    pGravity = 'pGravity', // Gravitational power
    pRollingResistance = 'pRollingResistance', // Rolling resistance power
    pWheelBearings = 'pWheelBearings', // Wheel bearings power
    pComputedTotalPower = 'pComputedTotalPower', // Power from acceleration
    pComputedWheelPower = 'pComputedWheelPower', // Wheel power from acceleration
    pComputedPower = 'pComputedPower', // Total power (watts)

    // Speed & Motion (4 properties)
    speed = 'speed', // Current speed (m/s)
    speedMax = 'speedMax', // Maximum speed (m/s)
    speedMaxIncline = 'speedMaxIncline', // Max speed on incline (m/s)
    virtSpeedCurrent = 'virtSpeedCurrent', // Virtual current speed (m/s)

    // Environmental (5 properties)
    temperature = 'temperature', // Temperature (celsius)
    windSpeed = 'windSpeed', // Wind speed (m/s)
    windDirection = 'windDirection', // Wind direction (radians)
    windBearing = 'windBearing', // Wind bearing (radians)
    windAlpha = 'windAlpha', // Wind angle (radians)

    // Physiological (2 properties)
    heartRate = 'heartRate', // Heart rate (bpm)
    cadence = 'cadence', // Pedaling cadence (rpm)
}

export const fieldToPointField: Record<PointFieldName, PointField> = {
    // Spatial & Navigation (7 properties)
    latitude: PointField.LATITUDE, // Latitude (radians)
    longitude: PointField.LONGITUDE, // Longitude (radians)
    elevation: PointField.ELEVATION, // Elevation (meters)
    bearing: PointField.BEARING, // Direction bearing (radians)
    distance: PointField.DISTANCE, // Distance (meters)
    radius: PointField.RADIUS, // Turn radius (meters)
    grade: PointField.GRADE, // Road grade/slope (%)

    // Temporal (2 properties)
    time: PointField.TIME, // Timestamp (ms since epoch)
    elapsed: PointField.ELAPSED, // Elapsed duration (ms)

    // Physics & Power (13 properties)
    pInputPower: PointField.P_INPUT_POWER, // GPX input power
    pCyclistProvidedOptimalPower: PointField.P_CYCLIST_PROVIDED_OPTIMAL_POWER, // Optimal power
    pCyclistPowerNeeded: PointField.P_CYCLIST_PROVIDED_POWER_NEEDED, // Power needed
    pCyclistProvidedMuscular: PointField.P_CYCLIST_PROVIDED_MUSCULAR, // Raw cyclist power
    PCyclistProvidedWheel: PointField.P_CYCLIST_PROVIDED_WHEEL, // Cyclist power transmitted to ground
    aeroCoef: PointField.AERO_COEF, // Aerodynamic coefficient
    pAero: PointField.P_AERO, // Aerodynamic power
    pGravity: PointField.P_GRAVITY, // Gravitational power
    pRollingResistance: PointField.P_ROLLING_RESISTANCE, // Rolling resistance power
    pWheelBearings: PointField.P_WHEEL_BEARINGS, // Wheel bearings power
    pComputedTotalPower: PointField.P_COMPUTED_TOTAL_POWER, // Power from acceleration
    pComputedWheelPower: PointField.P_COMPUTED_WHEEL_POWER, // Wheel power from acceleration
    pComputedPower: PointField.POWER, // Total power (watts)

    // Speed & Motion (4 properties)
    speed: PointField.SPEED, // Current speed (m/s)
    speedMax: PointField.SPEED_MAX, // Maximum speed (m/s)
    speedMaxIncline: PointField.SPEED_MAX_INCLINE, // Max speed on incline (m/s)
    virtSpeedCurrent: PointField.VIRT_SPEED_CURRENT, // Virtual current speed (m/s)

    // Environmental (5 properties)
    temperature: PointField.TEMPERATURE, // Temperature (celsius)
    windSpeed: PointField.WIND_SPEED, // Wind speed (m/s)
    windDirection: PointField.WIND_DIRECTION, // Wind direction (radians)
    windBearing: PointField.WIND_BEARING, // Wind bearing (radians)
    windAlpha: PointField.WIND_ALPHA, // Wind angle (radians)

    // Physiological (2 properties)
    heartRate: PointField.HEART_RATE, // Heart rate (bpm)
    cadence: PointField.CADENCE, // Pedaling cadence (rpm)
};

/**
 * Total number of fields per point in the chunked storage.
 */
export const FIELDS_PER_POINT = 33;

/**
 * Interface representing a complete point with all 33 properties.
 * All values are stored as numbers with appropriate unit conversions.
 *
 * Note: Angles are stored in RADIANS for efficient physics calculations.
 */
export interface Point {
    // Spatial & Navigation
    readonly latitude: number; // Latitude (radians)
    readonly longitude: number; // Longitude (radians)
    readonly elevation: number; // Elevation (meters)
    readonly bearing: number; // Direction bearing (radians)
    readonly distance: number; // Distance (meters)
    readonly radius: number; // Turn radius (meters)
    readonly grade: number; // Road grade/slope (%)

    // Temporal
    readonly time: number; // Timestamp (ms since epoch)
    readonly elapsed: number; // Elapsed duration (ms)

    // Physics & Power
    readonly pInputPower: number; // GPX input power
    readonly pCyclistProvidedOptimalPower: number; // Optimal power
    readonly pCyclistPowerNeeded: number; // Power needed
    readonly pCyclistProvidedMuscular: number; // Raw cyclist power
    readonly PCyclistProvidedWheel: number; // Cyclist power transmitted to ground
    readonly aeroCoef: number; // Aerodynamic coefficient
    readonly pAero: number; // Aerodynamic power
    readonly pGravity: number; // Gravitational power
    readonly pRollingResistance: number; // Rolling resistance power
    readonly pWheelBearings: number; // Wheel bearings power
    readonly pComputedTotalPower: number; // Power from acceleration
    readonly pComputedWheelPower: number; // Wheel power from acceleration
    readonly pComputedPower: number; // Total power (watts)

    // Speed & Motion
    readonly speed: number; // Current speed (m/s)
    readonly speedMax: number; // Maximum speed (m/s)
    readonly speedMaxIncline: number; // Max speed on incline (m/s)
    readonly virtSpeedCurrent: number; // Virtual current speed (m/s)

    // Environmental
    readonly temperature: number; // Temperature (celsius)
    readonly windSpeed: number; // Wind speed (m/s)
    readonly windDirection: number; // Wind direction (radians)
    readonly windBearing: number; // Wind bearing (radians)
    readonly windAlpha: number; // Wind angle (radians)

    // Physiological
    readonly heartRate: number; // Heart rate (bpm)
    readonly cadence: number; // Pedaling cadence (rpm)
}

type Writable<T> = {
    -readonly [K in keyof T]: T[K];
};

export type PointWritable = Writable<Point>;

export const EMPTY_POINT: Point = {
    // Spatial & Navigation
    latitude: NaN,
    longitude: NaN,
    elevation: NaN,
    bearing: NaN,
    distance: NaN,
    radius: NaN,
    grade: NaN,
    // Temporal
    time: NaN,
    elapsed: NaN,
    // Physics & Power
    pInputPower: NaN,
    pCyclistProvidedOptimalPower: NaN,
    pCyclistPowerNeeded: NaN,
    pCyclistProvidedMuscular: NaN,
    PCyclistProvidedWheel: NaN,
    aeroCoef: NaN,
    pAero: NaN,
    pGravity: NaN,
    pRollingResistance: NaN,
    pWheelBearings: NaN,
    pComputedTotalPower: NaN,
    pComputedWheelPower: NaN,
    pComputedPower: NaN,
    // Speed & Motion
    speed: NaN,
    speedMax: NaN,
    speedMaxIncline: NaN,
    virtSpeedCurrent: NaN,
    // Environmental
    temperature: NaN,
    windSpeed: NaN,
    windDirection: NaN,
    windBearing: NaN,
    windAlpha: NaN,
    // Physiological
    heartRate: NaN,
    cadence: NaN,
};
