// ⚠️ THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-point-path.ts
// Source: src/codegen/field-definitions.ts
// To modify: Update field-definitions.ts and run: npm run generate:point

/**
 * Enum defining the index of each field in the chunked array storage.
 * Based on PropertyKeys.java from gpx2web project.
 * Each point has exactly 31 numeric values stored contiguously.
 */
export enum PointField {
    // Spatial & Navigation (6 properties)
    LAT = 0, // Latitude (radians)
    LON = 1, // Longitude (radians)
    ELE = 2, // Elevation (meters)
    BEARING = 3, // Direction bearing (radians)
    DIST = 4, // Distance (meters)
    RADIUS = 5, // Turn radius (meters)

    // Temporal (2 properties)
    TIME = 6, // Timestamp (ms since epoch)
    ELAPSED = 7, // Elapsed duration (ms)

    // Physics & Power (12 properties)
    POWER = 8, // Total power (watts)
    P_CYCLIST_RAW = 9, // Raw cyclist power
    P_CYCLIST_WHEEL = 10, // Cyclist wheel power
    P_CYCLIST_OPTIMAL_POWER = 11, // Optimal power
    P_AERO = 12, // Aerodynamic power
    P_GRAVITY = 13, // Gravitational power
    P_ROLLING_RESISTANCE = 14, // Rolling resistance power
    P_WHEEL_BEARINGS = 15, // Wheel bearings power
    P_POWER_FROM_ACC = 16, // Power from acceleration
    P_POWER_WHEEL_FROM_ACC = 17, // Wheel power from acceleration
    AERO_COEF = 18, // Aerodynamic coefficient
    GRADE = 19, // Road grade/slope (%)

    // Speed & Motion (4 properties)
    SPEED = 20, // Current speed (m/s)
    SPEED_MAX = 21, // Maximum speed (m/s)
    SPEED_MAX_INCLINE = 22, // Max speed on incline (m/s)
    VIRT_SPEED_CURRENT = 23, // Virtual current speed (m/s)

    // Environmental (5 properties)
    TEMPERATURE = 24, // Temperature (celsius)
    WIND_SPEED = 25, // Wind speed (m/s)
    WIND_DIRECTION = 26, // Wind direction (radians)
    WIND_BEARING = 27, // Wind bearing (radians)
    WIND_ALPHA = 28, // Wind angle (radians)

    // Physiological (2 properties)
    HEART_RATE = 29, // Heart rate (bpm)
    CADENCE = 30, // Pedaling cadence (rpm)
}

export enum PointFieldName {
    // Spatial & Navigation (6 properties)
    lat = 'lat', // Latitude (radians)
    lon = 'lon', // Longitude (radians)
    ele = 'ele', // Elevation (meters)
    bearing = 'bearing', // Direction bearing (radians)
    dist = 'dist', // Distance (meters)
    radius = 'radius', // Turn radius (meters)

    // Temporal (2 properties)
    time = 'time', // Timestamp (ms since epoch)
    elapsed = 'elapsed', // Elapsed duration (ms)

    // Physics & Power (12 properties)
    power = 'power', // Total power (watts)
    pCyclistRaw = 'pCyclistRaw', // Raw cyclist power
    pCyclistWheel = 'pCyclistWheel', // Cyclist wheel power
    pCyclistOptimalPower = 'pCyclistOptimalPower', // Optimal power
    pAero = 'pAero', // Aerodynamic power
    pGravity = 'pGravity', // Gravitational power
    pRollingResistance = 'pRollingResistance', // Rolling resistance power
    pWheelBearings = 'pWheelBearings', // Wheel bearings power
    pPowerFromAcc = 'pPowerFromAcc', // Power from acceleration
    pPowerWheelFromAcc = 'pPowerWheelFromAcc', // Wheel power from acceleration
    aeroCoef = 'aeroCoef', // Aerodynamic coefficient
    grade = 'grade', // Road grade/slope (%)

    // Speed & Motion (4 properties)
    speed = 'speed', // Current speed (m/s)
    speedMax = 'speedMax', // Maximum speed (m/s)
    speedMaxIncline = 'speedMaxIncline', // Max speed on incline (m/s)
    virtSpeedCurrent = 'virtSpeedCurrent', // Virtual current speed (m/s)

    // Environmental (5 properties)
    temperature = 'temperature', // Temperature (celsius)
    windSpeed = 'windSpeed', // Wind speed (m/s)
    windDirection = 'windDirection', // Wind direction (radians)
    windBearing = 'windBearing', // Wind bearing (radians)
    windAlpha = 'windAlpha', // Wind angle (radians)

    // Physiological (2 properties)
    heartRate = 'heartRate', // Heart rate (bpm)
    cadence = 'cadence', // Pedaling cadence (rpm)
}

export const fieldToPointField: Record<PointFieldName, PointField> = {
    // Spatial & Navigation (6 properties)
    lat: PointField.LAT, // Latitude (radians)
    lon: PointField.LON, // Longitude (radians)
    ele: PointField.ELE, // Elevation (meters)
    bearing: PointField.BEARING, // Direction bearing (radians)
    dist: PointField.DIST, // Distance (meters)
    radius: PointField.RADIUS, // Turn radius (meters)

    // Temporal (2 properties)
    time: PointField.TIME, // Timestamp (ms since epoch)
    elapsed: PointField.ELAPSED, // Elapsed duration (ms)

    // Physics & Power (12 properties)
    power: PointField.POWER, // Total power (watts)
    pCyclistRaw: PointField.P_CYCLIST_RAW, // Raw cyclist power
    pCyclistWheel: PointField.P_CYCLIST_WHEEL, // Cyclist wheel power
    pCyclistOptimalPower: PointField.P_CYCLIST_OPTIMAL_POWER, // Optimal power
    pAero: PointField.P_AERO, // Aerodynamic power
    pGravity: PointField.P_GRAVITY, // Gravitational power
    pRollingResistance: PointField.P_ROLLING_RESISTANCE, // Rolling resistance power
    pWheelBearings: PointField.P_WHEEL_BEARINGS, // Wheel bearings power
    pPowerFromAcc: PointField.P_POWER_FROM_ACC, // Power from acceleration
    pPowerWheelFromAcc: PointField.P_POWER_WHEEL_FROM_ACC, // Wheel power from acceleration
    aeroCoef: PointField.AERO_COEF, // Aerodynamic coefficient
    grade: PointField.GRADE, // Road grade/slope (%)

    // Speed & Motion (4 properties)
    speed: PointField.SPEED, // Current speed (m/s)
    speedMax: PointField.SPEED_MAX, // Maximum speed (m/s)
    speedMaxIncline: PointField.SPEED_MAX_INCLINE, // Max speed on incline (m/s)
    virtSpeedCurrent: PointField.VIRT_SPEED_CURRENT, // Virtual current speed (m/s)

    // Environmental (5 properties)
    temperature: PointField.TEMPERATURE, // Temperature (celsius)
    windSpeed: PointField.WIND_SPEED, // Wind speed (m/s)
    windDirection: PointField.WIND_DIRECTION, // Wind direction (radians)
    windBearing: PointField.WIND_BEARING, // Wind bearing (radians)
    windAlpha: PointField.WIND_ALPHA, // Wind angle (radians)

    // Physiological (2 properties)
    heartRate: PointField.HEART_RATE, // Heart rate (bpm)
    cadence: PointField.CADENCE, // Pedaling cadence (rpm)
};

/**
 * Total number of fields per point in the chunked storage.
 */
export const FIELDS_PER_POINT = 31;

/**
 * Interface representing a complete point with all 31 properties.
 * All values are stored as numbers with appropriate unit conversions.
 *
 * Note: Angles are stored in RADIANS for efficient physics calculations.
 */
export interface Point {
    // Spatial & Navigation
    readonly lat: number; // Latitude (radians)
    readonly lon: number; // Longitude (radians)
    readonly ele: number; // Elevation (meters)
    readonly bearing: number; // Direction bearing (radians)
    readonly dist: number; // Distance (meters)
    readonly radius: number; // Turn radius (meters)

    // Temporal
    readonly time: number; // Timestamp (ms since epoch)
    readonly elapsed: number; // Elapsed duration (ms)

    // Physics & Power
    readonly power: number; // Total power (watts)
    readonly pCyclistRaw: number; // Raw cyclist power
    readonly pCyclistWheel: number; // Cyclist wheel power
    readonly pCyclistOptimalPower: number; // Optimal power
    readonly pAero: number; // Aerodynamic power
    readonly pGravity: number; // Gravitational power
    readonly pRollingResistance: number; // Rolling resistance power
    readonly pWheelBearings: number; // Wheel bearings power
    readonly pPowerFromAcc: number; // Power from acceleration
    readonly pPowerWheelFromAcc: number; // Wheel power from acceleration
    readonly aeroCoef: number; // Aerodynamic coefficient
    readonly grade: number; // Road grade/slope (%)

    // Speed & Motion
    readonly speed: number; // Current speed (m/s)
    readonly speedMax: number; // Maximum speed (m/s)
    readonly speedMaxIncline: number; // Max speed on incline (m/s)
    readonly virtSpeedCurrent: number; // Virtual current speed (m/s)

    // Environmental
    readonly temperature: number; // Temperature (celsius)
    readonly windSpeed: number; // Wind speed (m/s)
    readonly windDirection: number; // Wind direction (radians)
    readonly windBearing: number; // Wind bearing (radians)
    readonly windAlpha: number; // Wind angle (radians)

    // Physiological
    readonly heartRate: number; // Heart rate (bpm)
    readonly cadence: number; // Pedaling cadence (rpm)
}

type Writable<T> = {
    -readonly [K in keyof T]: T[K];
};

export type PointWritable = Writable<Point>;

export const EMPTY_POINT: Point = {
    // Spatial & Navigation
    lat: NaN,
    lon: NaN,
    ele: NaN,
    bearing: NaN,
    dist: NaN,
    radius: NaN,
    // Temporal
    time: NaN,
    elapsed: NaN,
    // Physics & Power
    power: NaN,
    pCyclistRaw: NaN,
    pCyclistWheel: NaN,
    pCyclistOptimalPower: NaN,
    pAero: NaN,
    pGravity: NaN,
    pRollingResistance: NaN,
    pWheelBearings: NaN,
    pPowerFromAcc: NaN,
    pPowerWheelFromAcc: NaN,
    aeroCoef: NaN,
    grade: NaN,
    // Speed & Motion
    speed: NaN,
    speedMax: NaN,
    speedMaxIncline: NaN,
    virtSpeedCurrent: NaN,
    // Environmental
    temperature: NaN,
    windSpeed: NaN,
    windDirection: NaN,
    windBearing: NaN,
    windAlpha: NaN,
    // Physiological
    heartRate: NaN,
    cadence: NaN,
};
