#!/usr/bin/env node
/**
 * Code generator for Point.ts and Path.ts accessor methods.
 *
 * This script generates TypeScript code from field definitions.
 * Run: npm run generate:point
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { FIELD_DEFINITIONS, TOTAL_FIELD_COUNT } from './field-definitions';

const PROJECT_ROOT = resolve(__dirname, '..');

/**
 * Convert field property name to PascalCase for method names.
 * Examples: lat -> Latitude, pCyclistRaw -> PCyclistRaw
 */
function toPascalCase(prop: string): string {
    // Handle special cases like pCyclistRaw -> PCyclistRaw
    if (prop.startsWith('p') && prop.charAt(1) === prop.charAt(1).toUpperCase()) {
        return prop.charAt(0).toUpperCase() + prop.slice(1);
    }
    return prop.charAt(0).toUpperCase() + prop.slice(1);
}

/**
 * Generate Point.ts file completely.
 */
function generatePointFile() {
    console.log('🔨 Generating Point.ts...');

    const lines: string[] = [];

    // Header
    lines.push('// ⚠️ THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY');
    lines.push('// Generated by: scripts/generate-point-path.ts');
    lines.push('// Source: src/codegen/field-definitions.ts');
    lines.push('// To modify: Update field-definitions.ts and run: npm run generate:point');
    lines.push('');

    // PointField enum
    lines.push('/**');
    lines.push(' * Enum defining the index of each field in the chunked array storage.');
    lines.push(' * Based on PropertyKeys.java from gpx2web project.');
    lines.push(
        ` * Each point has exactly ${TOTAL_FIELD_COUNT} numeric values stored contiguously.`
    );
    lines.push(' */');
    lines.push('export enum PointField {');

    let i = 0;
    for (const category of FIELD_DEFINITIONS) {
        lines.push(`    // ${category.name} (${category.fields.length} properties)`);

        for (const field of category.fields) {
            lines.push(`    ${field.name} = ${i++}, // ${field.comment}`);
        }
        lines.push('');
    }

    lines.push('}');
    lines.push('');
    lines.push('export enum PointFieldName {');

    for (const category of FIELD_DEFINITIONS) {
        lines.push(`    // ${category.name} (${category.fields.length} properties)`);

        for (const field of category.fields) {
            lines.push(`    ${field.prop} = '${field.prop}', // ${field.comment}`);
        }
        lines.push('');
    }

    lines.push('}');
    lines.push('');

    lines.push('export const fieldToPointField: Record<PointFieldName, PointField> = {');

    for (const category of FIELD_DEFINITIONS) {
        lines.push(`    // ${category.name} (${category.fields.length} properties)`);

        for (const field of category.fields) {
            lines.push(`    ${field.prop}: PointField.${field.name}, // ${field.comment}`);
        }
        lines.push('');
    }

    lines.push('}');
    lines.push('');

    // FIELDS_PER_POINT constant
    lines.push('/**');
    lines.push(' * Total number of fields per point in the chunked storage.');
    lines.push(' */');
    lines.push(`export const FIELDS_PER_POINT = ${i};`);
    lines.push('');

    // Point interface
    lines.push('/**');
    lines.push(
        ` * Interface representing a complete point with all ${TOTAL_FIELD_COUNT} properties.`
    );
    lines.push(' * All values are stored as numbers with appropriate unit conversions.');
    lines.push(' *');
    lines.push(' * Note: Angles are stored in RADIANS for efficient physics calculations.');
    lines.push(' */');
    lines.push('export interface Point {');

    for (const category of FIELD_DEFINITIONS) {
        lines.push(`    // ${category.name}`);

        for (const field of category.fields) {
            lines.push(`    readonly ${field.prop}: number; // ${field.comment}`);
        }
        lines.push('');
    }

    lines.push('}');
    lines.push('');

    // PointWritable type
    lines.push('type Writable<T> = {');
    lines.push('    -readonly [K in keyof T]: T[K];');
    lines.push('};');
    lines.push('');
    lines.push('export type PointWritable = Writable<Point>;');
    lines.push('');

    // EMPTY_POINT constant
    lines.push('export const EMPTY_POINT: Point = {');

    for (const category of FIELD_DEFINITIONS) {
        lines.push(`    // ${category.name}`);

        for (const field of category.fields) {
            lines.push(`    ${field.prop}: NaN,`);
        }
    }

    lines.push('};');

    // Write to file
    const content = lines.join('\n') + '\n';
    const filePath = resolve(PROJECT_ROOT, 'types/path/Point.ts');
    writeFileSync(filePath, content, 'utf-8');

    console.log(`✅ Generated Point.ts`);
}

/**
 * Generate Point.ts file completely.
 */
function generateAbstractPathFile() {
    console.log('🔨 Generating Point.ts...');

    const lines: string[] = [];

    // Header
    lines.push('// ⚠️ THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY');
    lines.push('// Generated by: scripts/generate-point-path.ts');
    lines.push('// Source: src/codegen/field-definitions.ts');
    lines.push('// To modify: Update field-definitions.ts and run: npm run generate:point');
    lines.push('');

    lines.push("import { toDegrees } from '@/utils/';");
    lines.push("import { FIELDS_PER_POINT, Point, PointField } from './Point';");
    lines.push("import { AbstractPath } from './AbstractPath';");

    lines.push('export abstract class GeneratedPath extends AbstractPath {');

    // Generate Path.ts methods (output to console for manual review)
    console.log('\n📝 Generated Path.ts methods:');
    console.log('='.repeat(80));
    console.log('\n// Accessor methods:');
    generatePathAccessors(lines);
    lines.push('');
    console.log('\n// addPoint method:');
    generateAddPointMethod(lines);
    lines.push('');
    console.log('\n// getPointData method:');
    generateGetPointDataMethod(lines);
    lines.push('');
    console.log('\n// interpolatePoint method:');
    generateInterpolatePointMethod(lines);
    lines.push('');
    console.log('='.repeat(80));
    lines.push('}');

    // Write to file
    const content = lines.join('\n') + '\n';
    const filePath = resolve(PROJECT_ROOT, 'types/path/GeneratedPath.ts');
    writeFileSync(filePath, content, 'utf-8');

    console.log(`✅ Generated AbstractPath.ts`);
}

/**
 * Generate accessor methods for Path.ts
 * Returns the generated method code as a string
 */
function generatePathAccessors(lines: string[]) {
    console.log('🔨 Generating Path.ts accessor methods...');

    // Group fields by category for better organization
    for (const category of FIELD_DEFINITIONS) {
        lines.push(`    // === ${category.name} Accessors ===`);
        lines.push('');

        for (const field of category.fields) {
            const pascalName = field.methodName || toPascalCase(field.prop);

            // Standard getter
            lines.push(`    get${pascalName}(pointIndex: number): number {`);
            lines.push(`        return super.getField(pointIndex, PointField.${field.name});`);
            lines.push(`    }`);
            lines.push('');

            // Degree variant getter
            if (field.getDegrees) {
                lines.push(`    get${pascalName}Deg(pointIndex: number): number {`);
                lines.push(
                    `        return toDegrees(super.getField(pointIndex, PointField.${field.name}));`
                );
                lines.push(`    }`);
                lines.push('');
            }

            // Standard setter
            const setterParam = field.setSpecial === 'date' ? 'number | Date' : 'number';
            lines.push(`    set${pascalName}(pointIndex: number, value: ${setterParam}): void {`);

            if (field.setSpecial === 'date') {
                lines.push(
                    `        const timestamp = value instanceof Date ? value.getTime() : value;`
                );
                lines.push(
                    `        super.setField(pointIndex, PointField.${field.name}, timestamp);`
                );
            } else {
                lines.push(`        super.setField(pointIndex, PointField.${field.name}, value);`);
            }

            lines.push(`    }`);
            lines.push('');

            // Special getter variant
            if (field.getSpecial === 'date') {
                lines.push(`    get${pascalName}AsDate(pointIndex: number): Date {`);
                lines.push(`        return new Date(this.get${pascalName}(pointIndex));`);
                lines.push(`    }`);
                lines.push('');
            }
        }
    }
}

/**
 * Generate addPoint method implementation
 */

function generateAddPointMethod(lines: string[]) {
    console.log('🔨 Generating addPoint method...');

    lines.push('    /**');
    lines.push('     * Adds a new point with the provided data.');
    lines.push(`     * @param data Complete point data with all ${TOTAL_FIELD_COUNT} properties`);
    lines.push('     * @returns The index of the newly added point');
    lines.push('     */');
    lines.push('    addPoint(data: Point): number {');
    lines.push('        const pointIndex = this.pointCount;');
    lines.push('        this.ensureCapacity(pointIndex + 1);');
    lines.push('');
    lines.push('        // Increment point count first so bounds checking works');
    lines.push('        this.pointCount++;');
    lines.push('');
    lines.push('        // Set all fields from the provided data');

    for (const category of FIELD_DEFINITIONS) {
        lines.push(`        // ${category.name}`);

        for (const field of category.fields) {
            const pascalName = field.methodName || toPascalCase(field.prop);
            lines.push(`        this.set${pascalName}(pointIndex, data.${field.prop});`);
        }
        lines.push('');
    }

    lines.push('        return pointIndex;');
    lines.push('    }');
}

/**
 * Generate getPointData method implementation
 */
function generateGetPointDataMethod(lines: string[]) {
    console.log('🔨 Generating getPointData method...');

    lines.push('    /**');
    lines.push('     * Gets all data for a specific point.');
    lines.push('     */');
    lines.push('    getPointData(pointIndex: number): Point {');
    lines.push('        return {');

    for (const category of FIELD_DEFINITIONS) {
        lines.push(`            // ${category.name}`);

        for (const field of category.fields) {
            const pascalName = field.methodName || toPascalCase(field.prop);
            lines.push(`            ${field.prop}: this.get${pascalName}(pointIndex),`);
        }
    }

    lines.push('        };');
    lines.push('    }');
}

/**
 * Generate interpolatePoint method implementation
 */
function generateInterpolatePointMethod(lines: string[]) {
    console.log('🔨 Generating interpolatePoint method...');

    lines.push('        // Helper function for strict NaN handling');
    lines.push(
        '        protected interpolateValue(v1: number, v2: number, coef: number): number {'
    );
    lines.push('            if (isNaN(v1) || isNaN(v2)) {');
    lines.push('                return NaN;');
    lines.push('            }');
    lines.push('            return v1 + (v2 - v1) * coef;');
    lines.push('        };');
    lines.push('');

    lines.push('    /**');
    lines.push('     * Interpolates a new point between two existing points.');
    lines.push('     *');
    lines.push('     * Uses linear interpolation for all numeric fields:');
    lines.push('     * - result = p1 + (p2 - p1) × coef');
    lines.push('     *');
    lines.push('     * **NaN Handling (STRICT):**');
    lines.push('     * - If either p1 or p2 value is NaN, result is NaN');
    lines.push('     * - This ensures data integrity for incomplete GPS data');
    lines.push('     *');
    lines.push('     * @param index1 Index of first point');
    lines.push('     * @param index2 Index of second point');
    lines.push('     * @param coef Interpolation coefficient (0 = p1, 1 = p2, 0.5 = midpoint)');
    lines.push('     * @returns Interpolated point');
    lines.push('     */');
    lines.push(
        '    public interpolatePoint(index1: number, index2: number, coef: number): Point {'
    );
    lines.push('        const p1 = this.getPointData(index1);');
    lines.push('        const p2 = this.getPointData(index2);');
    lines.push('');
    lines.push('        return {');

    for (const category of FIELD_DEFINITIONS) {
        lines.push(`            // ${category.name}`);

        for (const field of category.fields) {
            lines.push(
                `            ${field.prop}: this.interpolateValue(p1.${field.prop}, p2.${field.prop}, coef),`
            );
        }
    }

    lines.push('        };');
    lines.push('    }');
}

/**
 * Main generation function
 */
function main() {
    console.log('🚀 Starting code generation...\n');

    // Generate Point.ts
    generatePointFile();
    generateAbstractPathFile();

    console.log('\n✅ Code generation complete!');
    console.log('\n⚠️  Note: Path.ts methods printed above for review.');
    console.log('   These can be manually copied into Path.ts or automated in future versions.');
}

// Run the generator
main();
