/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BikeTab: typeof import('./src/components/BikeTab.vue')['default']
    ConfigModal: typeof import('./src/components/ConfigModal.vue')['default']
    CyclistTab: typeof import('./src/components/CyclistTab.vue')['default']
    DataChart: typeof import('./src/components/DataChart.vue')['default']
    EnhanceOptionsTab: typeof import('./src/components/EnhanceOptionsTab.vue')['default']
    FieldsSidebar: typeof import('./src/components/FieldsSidebar.vue')['default']
    FileSection: typeof import('./src/components/FileSection.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    PowerTab: typeof import('./src/components/PowerTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderInput: typeof import('./src/components/SliderInput.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    WindTab: typeof import('./src/components/WindTab.vue')['default']
  }
}
