/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BikeTab: typeof import('./src/components/BikeTab.vue')['default']
    ConfigModal: typeof import('./src/components/ConfigModal.vue')['default']
    CyclistTab: typeof import('./src/components/CyclistTab.vue')['default']
    DataChart: typeof import('./src/components/DataChart.vue')['default']
    EnhanceOptionsTab: typeof import('./src/components/EnhanceOptionsTab.vue')['default']
    FieldsSidebar: typeof import('./src/components/FieldsSidebar.vue')['default']
    FileSection: typeof import('./src/components/FileSection.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    PowerTab: typeof import('./src/components/PowerTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderInput: typeof import('./src/components/SliderInput.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    UAccordion: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UCollapsible: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UDrawer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    URadioGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlider: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    WindTab: typeof import('./src/components/WindTab.vue')['default']
  }
}
